version: "3"

networks:
  laravel:


services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    image: firdaus452maulana/telemedicine-new:v1